/**
 * MemoryEngine — AI 自动记忆引擎
 * ----------------------------------------------------
 * 核心能力:
 *   - 对话结束时自动提取关键信息写入记忆
 *   - 长时间任务完成后自动更新项目记忆
 *   - 加载项目规则、代码规范、用户角色记忆
 *   - 记忆自动更新/添加/删除
 *
 * 设计参考: Claude Code 模式的上下文管理
 *   - 角色记忆 (你是谁)
 *   - 项目规范 (项目规则)
 *   - 代码规范 (编码风格)
 *   - 用户自定义规则
 *   - 会话记忆 (关键决策/上下文)
 */
import { useChatStore } from '../store/chatStore';

export interface MemoryEntry {
  id: string;
  type: 'role' | 'project_rule' | 'code_rule' | 'user_custom' | 'session_memory';
  title: string;
  content: string;
  tags: string[];
  createdAt: number;
  updatedAt: number;
  workspace?: string;
  /** 自动生成标记 */
  autoGenerated?: boolean;
}

export interface ProjectMemory {
  projectName: string;
  workspace: string;
  rules: MemoryEntry[];
  memories: MemoryEntry[];
  lastUpdated: number;
}

const MEMORY_STORAGE_KEY = 'agentai.memories';
const PROJECT_MEMORY_KEY = 'agentai.project_memory';

class MemoryEngineImpl {
  private memories: MemoryEntry[] = [];
  private projectMemory: Record<string, ProjectMemory> = {};
  private serverMemories: any[] = []; // 后端记忆缓存
  private lastServerFetch = 0;

  constructor() {
    this.load();
  }

  // ===== 持久化 =====
  private load() {
    try {
      const raw = localStorage.getItem(MEMORY_STORAGE_KEY);
      if (raw) this.memories = JSON.parse(raw);
      const proj = localStorage.getItem(PROJECT_MEMORY_KEY);
      if (proj) this.projectMemory = JSON.parse(proj);
    } catch { /* ignore */ }
  }

  private save() {
    try {
      localStorage.setItem(MEMORY_STORAGE_KEY, JSON.stringify(this.memories));
      localStorage.setItem(PROJECT_MEMORY_KEY, JSON.stringify(this.projectMemory));
    } catch { /* ignore */ }
  }

  // ===== 从后端同步记忆 =====
  async syncFromServer(workspace?: string): Promise<number> {
    // 5秒内不重复请求
    if (Date.now() - this.lastServerFetch < 5000) return this.serverMemories.length;
    try {
      const ws = workspace || '/';
      const r = await fetch(`/v1/memory?userId=default&workspace=${encodeURIComponent(ws)}&limit=30`);
      const data = await r.json();
      if (data.ok && data.memories) {
        this.serverMemories = data.memories;
        this.lastServerFetch = Date.now();
        // 将后端记忆合并到前端 (不重复)
        for (const sm of data.memories) {
          const exists = this.memories.some(m =>
            m.type === 'session_memory' && m.content.includes(sm.content?.slice(0, 50))
          );
          if (!exists && sm.content) {
            this.add({
              type: 'session_memory',
              title: `[服务器] ${sm.metadata?.name || new Date(sm.ts).toLocaleString('zh-CN')}`,
              content: sm.content,
              tags: ['server', sm.source || 'unknown'],
              workspace,
              autoGenerated: true,
            });
          }
        }
      }
      return this.serverMemories.length;
    } catch {
      return this.serverMemories.length;
    }
  }

  // ===== 基础 CRUD =====
  getAll(): MemoryEntry[] {
    return [...this.memories].sort((a, b) => b.updatedAt - a.updatedAt);
  }

  getByType(type: MemoryEntry['type']): MemoryEntry[] {
    return this.memories.filter(m => m.type === type).sort((a, b) => b.updatedAt - a.updatedAt);
  }

  getByWorkspace(workspace: string): MemoryEntry[] {
    return this.memories.filter(m => !m.workspace || m.workspace === workspace)
      .sort((a, b) => b.updatedAt - a.updatedAt);
  }

  add(entry: Omit<MemoryEntry, 'id' | 'createdAt' | 'updatedAt'>): MemoryEntry {
    const now = Date.now();
    const newEntry: MemoryEntry = {
      ...entry,
      id: `mem-${now}-${Math.random().toString(36).slice(2, 6)}`,
      createdAt: now,
      updatedAt: now,
    };
    this.memories.push(newEntry);
    this.save();
    return newEntry;
  }

  update(id: string, updates: Partial<MemoryEntry>): boolean {
    const idx = this.memories.findIndex(m => m.id === id);
    if (idx === -1) return false;
    this.memories[idx] = { ...this.memories[idx], ...updates, updatedAt: Date.now() };
    this.save();
    return true;
  }

  delete(id: string): boolean {
    const idx = this.memories.findIndex(m => m.id === id);
    if (idx === -1) return false;
    this.memories.splice(idx, 1);
    this.save();
    return true;
  }

  // ===== 项目记忆 =====
  getProjectMemory(workspace: string): ProjectMemory | null {
    return this.projectMemory[workspace] || null;
  }

  updateProjectMemory(workspace: string, memory: Partial<ProjectMemory>) {
    const existing = this.projectMemory[workspace] || {
      projectName: workspace.split(/[\\/]/).pop() || workspace,
      workspace,
      rules: [],
      memories: [],
      lastUpdated: Date.now(),
    };
    Object.assign(existing, memory, { lastUpdated: Date.now() });
    this.projectMemory[workspace] = existing;
    this.save();
  }

  // ===== 智能提取并保存记忆 (从对话内容) =====
  async extractAndSaveMemory(
    messages: Array<{ role: string; content: string }>,
    workspace: string,
    taskDesc?: string,
  ): Promise<MemoryEntry | null> {
    // 提取最后几条消息的关键信息
    const recentMessages = messages.slice(-10);
    let keyContent = '';

    // 从 assistant 回复中提取关键决策/结论
    for (const msg of recentMessages) {
      if (msg.role === 'assistant') {
        const decisionMatch = msg.content.match(/##\s*(决策|决定|方案|结论)[：:]([^#]+)/);
        if (decisionMatch) {
          keyContent += `[决策] ${decisionMatch[2].trim()}\n`;
        }
        const summaryMatch = msg.content.match(/##\s*(总结|摘要|完成|结果)[：:]([^#]+)/);
        if (summaryMatch) {
          keyContent += `[完成] ${summaryMatch[2].trim()}\n`;
        }
      }
    }

    if (!keyContent) return null;

    const entry = this.add({
      type: 'session_memory',
      title: taskDesc
        ? `[${new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })}] ${taskDesc}`
        : `会话记忆 ${new Date().toLocaleString('zh-CN')}`,
      content: keyContent,
      tags: ['auto', workspace.split(/[\\/]/).pop() || 'default'],
      workspace,
      autoGenerated: true,
    });

    // 也更新项目记忆
    const proj = this.getProjectMemory(workspace);
    if (proj) {
      proj.memories.push(entry);
      proj.lastUpdated = Date.now();
      this.save();
    }

    return entry;
  }

  // ===== 自动记忆: 任务完成/对话关闭时触发 =====
  async autoSaveOnTaskComplete(
    messages: Array<{ role: string; content: string }>,
    workspace: string,
    taskDesc: string,
  ) {
    return this.extractAndSaveMemory(messages, workspace, taskDesc);
  }

  // ===== 加载项目上下文 (规则/规范) =====
  getContextForWorkspace(workspace: string): string {
    const proj = this.projectMemory[workspace];
    const mems = this.getByWorkspace(workspace);
    const rules = this.getByType('project_rule');
    const codeRules = this.getByType('code_rule');
    const role = this.getByType('role');

    const parts: string[] = [];

    // 角色记忆
    if (role.length > 0) {
      parts.push(`[角色设定]\n${role[role.length - 1].content}`);
    }

    // 项目规则
    if (rules.length > 0) {
      parts.push(`[项目规则]\n${rules.map(r => `- ${r.title}: ${r.content}`).join('\n')}`);
    }

    // 代码规范
    if (codeRules.length > 0) {
      parts.push(`[代码规范]\n${codeRules.map(r => `- ${r.title}: ${r.content}`).join('\n')}`);
    }

    // 项目记忆
    if (proj && proj.memories.length > 0) {
      const recent = proj.memories.slice(-5);
      parts.push(`[项目记忆]\n${recent.map(m => `- ${m.title}: ${m.content}`).join('\n')}`);
    }

    return parts.join('\n\n');
  }

  // ===== 清除全部 =====
  clearAll() {
    this.memories = [];
    this.projectMemory = {};
    this.save();
  }
}

/** 全局单例 */
export const MemoryEngine = new MemoryEngineImpl();
